services:
 
  redisChicoliroLocal:
    container_name: 'redis'
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=fddfsdf3324k3l4k32
      - REDIS_PORT_NUMBER=6000
    command: /opt/bitnami/scripts/redis/run.sh
    restart: unless-stopped
    ports:
      - '6000:6000'
    volumes:
      - redisChicoliroLocal:/data
volumes:
  redisChicoliroLocal:
    driver: local
