name: New Bug Report
description: Report a Bug in the ChicoLiro Project
title: "[BUG]: <Título BREVE do bug>"
labels: ["BUG"]
projects: ["pi1-2024-ChicoLiro/ChicoLiro-Board"]
body:
  - type: textarea
    id: text-zone1
    attributes:
      label: Descreva o bug e o erro testemunhado
      description: Como é o comportamento do erro no sistema?
      placeholder: Digite...
    validations:
      required: true
  - type: textarea
    id: text-zone2
    attributes:
      label: Quais os passos necessário para reproduzir o bug?
      description: Escreva o passo a passo para que o bug aconteça.
      value: |
        - Faça '...'
        - Depois faça '...'
        - Teste '...'
    validations:
      required: true
  - type: textarea
    id: text-zone3
    attributes:
      label: Você suspeita de onde vem tal bug?
      description: Escreva o nome do arquivo seguida da parte do código que você suspeita de onde vem o erro.
      placeholder: |
        Arquivo: Pasta/Pasta/nomeArquivo.js
        __
        Cole o código aqui
      render: c++
  - type: textarea
    id: text-zone4
    attributes:
      label: Detalhes adicionais?
      description: Escreve se houver detalhes necessários de estar à conhecimento de todos.
      placeholder: |
        Escreva ou deixe em branco.
