#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running some tests before push...'
npm run test ||
(echo 'Some test failed, fix it before pushing.' && exit 1)

npm run build
(echo 'Project build failed, check and fix the failures.' && exit 1)

echo 'Done!'